<?php
/**
 * Created by PhpStorm.
 * User: ivan
 * Date: 03.12.17
 * Time: 18:00
 */
namespace Ivan\CreditCalcBundle\Form;
use Ivan\CreditCalcBundle\Document\CreditRequest;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CreditRequestForm extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('amount',NumberType::class,['label' => 'Сумма кредита ($):','required'=>true])
            ->add('period',NumberType::class,['label'=>'Срок кредитования (мес.):','required'=>true])
            ->add('percentage',NumberType::class,['label'=>'Процентная ставка:','required'=>true,'attr'=>['min'=>'0','max'=>'100']])
            ->add('first_payment_date',DateType::class,['label'=>'Дата первого платежа',
                'widget' => 'single_text', 'html5' => false,
                'attr' => ['class' => 'js-datepicker'],'required'=>true])
            ->add('calculate',SubmitType::class,['label'=>'Рассчитать','attr'=>['class'=>'btn btn-primary']]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => CreditRequest::class,
        )); // TODO: Change the autogenerated stub
    }
}